spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test
    password: test
  jpa:
    logging:
      level:
        org:
          hibernate:
            SQL: DEBUG
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  test:
    database:
      replace: none