spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org:
      springframework:
        beans:
          factory: DEBUG